
set(EDEPMANAGER ${Poetry_PREFIX} depmanager)
string(REPLACE ";" " " EDMGR "${EDEPMANAGER}")
execute_process(COMMAND ${EDEPMANAGER} info version --raw
        OUTPUT_VARIABLE depmanager_version
        RESULT_VARIABLE depmanager_check_result)
if (NOT depmanager_check_result EQUAL 0)
    message(FATAL_ERROR "Depmanager command '${EDMGR}' is not installed or not available in the Python environment. Please install Depmanager to manage third party dependencies.")
else ()
    string(STRIP ${depmanager_version} depmanager_version)
    string(REPLACE "depmanager" "" depmanager_version ${depmanager_version})
    string(REPLACE "version" "" depmanager_version ${depmanager_version})
    string(STRIP ${depmanager_version} depmanager_version)
    message(STATUS "Depmanager found: '${EDMGR}' version ${depmanager_version}")

    execute_process(COMMAND ${EDEPMANAGER} info cmakedir --raw
            OUTPUT_VARIABLE depmanager_cmake_dir)
    string(STRIP ${depmanager_cmake_dir} depmanager_cmake_dir)
    string(REPLACE "\\" "/" depmanager_cmake_dir ${depmanager_cmake_dir})
    string(REPLACE "\n" "" depmanager_cmake_dir ${depmanager_cmake_dir})
    string(REPLACE "\r" "" depmanager_cmake_dir ${depmanager_cmake_dir})
    message(STATUS "Depmanager cmake modules path: ${depmanager_cmake_dir}")
    if (NOT EXISTS ${depmanager_cmake_dir}/DepManager.cmake)
        message(FATAL_ERROR "Depmanager cmake modules not found at: ${depmanager_cmake_dir}")
    endif ()

    list(PREPEND CMAKE_MODULE_PATH ${depmanager_cmake_dir})
    include(DepManager)
endif ()

if (${${PROJECT_PREFIX}_BUILD_SHARED})
    set(LOCAL_KIND shared)
else ()
    set(LOCAL_KIND static)
endif ()

if (${PROJECT_PREFIX}_CROSS_COMPILATION)
    message(STATUS "Loading '${LOCAL_KIND}' third parties for ${${PROJECT_PREFIX}_ARCH_STR}")
    dm_load_environment(KIND ${LOCAL_KIND} ARCH ${${PROJECT_PREFIX}_ARCH_STR})
else ()
    message(STATUS "Loading '${LOCAL_KIND}' third parties for native")
    dm_load_environment(KIND ${LOCAL_KIND})
endif ()

dm_get_glibc(GLIBC_VERSION)
if (${GLIBC_VERSION})
    set(${PROJECT_PREFIX}_GLIBC_STR "glibc_${GLIBC_VERSION}")
endif ()
message(STATUS "Third parties loaded.")
message(STATUS "-----------------------------------")
message(STATUS "CMAKE_PREFIX_PATH:")
foreach (path IN LISTS CMAKE_PREFIX_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "CMAKE_MODULE_PATH:")
foreach (path IN LISTS CMAKE_MODULE_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "-----------------------------------")
